export class HosonhansuBean {
    nsID?:number;
    tenkhaisinh?:string;
    sohieu?:string;
    socmnd?:string;
    ngaysinh?:Date;
    phongbanId?:number;
    phongban?:string;
    loaiHDID?:number;
    vtriId?:number;
    nghecnktId?:number;
    nghecnkt?:string;
    ngayvaodonvi?:Date;
    ngayvaodonviHdld?:Date;
    nntruoctdId?:number;
    nganhSxkdId?:number;
    gioitinh?:boolean;
    donviId?:number;
    donvi?:string;
    donviKyhdld?:string;
}